import type { LucideIcon } from "lucide-react";
import {
  ArrowUpDown,
  Binary,
  Braces,
  Calendar,
  CaseSensitive,
  Code,
  CodeXml,
  CopyCheck,
  Database,
  Dices,
  FileCode,
  FileCode2,
  FileInput,
  FileJson,
  FileText,
  GitCompare,
  Globe,
  Hash,
  Key,
  KeyRound,
  Link,
  Lock,
  LockKeyhole,
  Monitor,
  Network,
  Palette,
  PlugZap,
  QrCode,
  Quote,
  RefreshCw,
  Regex,
  Shield,
  SlidersHorizontal,
  Sparkles,
  Split,
  Table,
  Terminal,
  TextCursorInput,
  Thermometer,
  Timer,
  UserRound,
  Waves,
  Circle,
} from "lucide-react";

/** Map design.pen lucide icon names → lucide-react components. */
const ICONS: Record<string, LucideIcon> = {
  braces: Braces,
  "file-code": FileCode,
  "file-json": FileJson,
  "file-braces": FileJson,
  quote: Quote,
  split: Split,
  sparkles: Sparkles,
  "git-compare": GitCompare,
  code: Code,
  "file-input": FileInput,
  table: Table,
  "code-xml": CodeXml,
  "file-code-2": FileCode2,
  database: Database,
  "file-text": FileText,
  binary: Binary,
  link: Link,
  hash: Hash,
  "text-cursor-input": TextCursorInput,
  "refresh-cw": RefreshCw,
  waves: Waves,
  "key-round": KeyRound,
  key: Key,
  "lock-keyhole": LockKeyhole,
  lock: Lock,
  shield: Shield,
  dices: Dices,
  globe: Globe,
  monitor: Monitor,
  "user-round": UserRound,
  terminal: Terminal,
  timer: Timer,
  network: Network,
  "case-sensitive": CaseSensitive,
  "arrow-up-down": ArrowUpDown,
  "copy-check": CopyCheck,
  regex: Regex,
  "sliders-horizontal": SlidersHorizontal,
  calendar: Calendar,
  "plug-zap": PlugZap,
  "qr-code": QrCode,
  palette: Palette,
  thermometer: Thermometer,
};

export function navIcon(name: string): LucideIcon {
  return ICONS[name] ?? Circle;
}
