import { defineTool } from "../define-tool";
import type { ToolDefinition, ToolFamilyId, ToolUiPattern } from "../types";

type PlannedToolSpec = {
  readonly id: string;
  readonly name: string;
  readonly family: ToolFamilyId;
  readonly pattern: ToolUiPattern;
  readonly description: string;
  readonly keywords: readonly string[];
  /** Pencil artboard name and stable node id in design/design.pen. */
  readonly designFrame: string;
};

const capabilityForPattern: Readonly<
  Record<ToolUiPattern, "transform-text" | "generate-value" | "inspect-text" | "compare-text">
> = {
  transform: "transform-text",
  generate: "generate-value",
  inspect: "inspect-text",
  diff: "compare-text",
};

function plannedTool(spec: PlannedToolSpec): ToolDefinition {
  const capability = capabilityForPattern[spec.pattern];
  return defineTool({
    ...spec,
    slug: spec.id,
    shortName: spec.name,
    status: "coming-soon",
    releaseStage: "planned",
    platforms: {
      web: { status: "planned", capabilities: [capability] },
      "browser-extension": { status: "planned", capabilities: [capability] },
      "vscode-extension": { status: "planned", capabilities: [capability] },
    },
  });
}

/**
 * The 63 non-reference tool definitions from the Pencil source of truth.
 * These are product contracts, not implementations: no item is navigable or
 * releasable until an owning agent supplies its core module, host adapters,
 * UI conformance tests, and release evidence.
 */
const plannedToolSpecs = [
  {
    id: "beautify-minify",
    name: "Beautify / Minify",
    family: "json-markup",
    pattern: "transform",
    description: "Format or compact structured code and data locally.",
    keywords: ["beautify", "minify", "format", "compact"],
    designFrame: "Beautify / Minify (T4mv0)",
  },
  {
    id: "json-diff",
    name: "JSON Diff",
    family: "json-markup",
    pattern: "diff",
    description: "Compare two JSON documents and inspect their differences.",
    keywords: ["json", "diff", "compare"],
    designFrame: "JSON Diff (lMoqW)",
  },
  {
    id: "json-toolbox",
    name: "JSON Toolbox",
    family: "json-markup",
    pattern: "inspect",
    description: "Validate, inspect, and work with JSON documents.",
    keywords: ["json", "validate", "inspect"],
    designFrame: "JSON Toolbox (NChG5)",
  },
  {
    id: "json-to-yaml",
    name: "JSON → YAML",
    family: "json-markup",
    pattern: "transform",
    description: "Convert JSON documents to YAML locally.",
    keywords: ["json", "yaml", "convert"],
    designFrame: "JSON → YAML (zVNls)",
  },
  {
    id: "yaml-to-json",
    name: "YAML → JSON",
    family: "json-markup",
    pattern: "transform",
    description: "Convert YAML documents to JSON locally.",
    keywords: ["yaml", "json", "convert"],
    designFrame: "YAML → JSON (z4tgms)",
  },
  {
    id: "json-to-csv",
    name: "JSON → CSV",
    family: "json-markup",
    pattern: "transform",
    description: "Convert JSON records to CSV locally.",
    keywords: ["json", "csv", "convert"],
    designFrame: "JSON → CSV (RLXps)",
  },
  {
    id: "json-to-toml",
    name: "JSON → TOML",
    family: "json-markup",
    pattern: "transform",
    description: "Convert JSON documents to TOML locally.",
    keywords: ["json", "toml", "convert"],
    designFrame: "JSON → TOML (heQcn)",
  },
  {
    id: "xml-formatter",
    name: "XML Formatter",
    family: "json-markup",
    pattern: "transform",
    description: "Format and validate XML without uploading it.",
    keywords: ["xml", "format", "validate"],
    designFrame: "XML Formatter (OWCch)",
  },
  {
    id: "sql-formatter",
    name: "SQL Formatter",
    family: "json-markup",
    pattern: "transform",
    description: "Format SQL queries for readable review.",
    keywords: ["sql", "format", "query"],
    designFrame: "SQL Formatter (iORC5)",
  },
  {
    id: "markdown-preview",
    name: "Markdown Preview",
    family: "json-markup",
    pattern: "inspect",
    description: "Preview Markdown with a local rendered output.",
    keywords: ["markdown", "preview", "md"],
    designFrame: "Markdown Preview (d3XcA)",
  },
  {
    id: "url-encode",
    name: "URL Encode",
    family: "encoding-text",
    pattern: "transform",
    description: "Encode or decode URL-safe text locally.",
    keywords: ["url", "encode", "decode", "percent"],
    designFrame: "URL Encode (C2SF76)",
  },
  {
    id: "html-entities",
    name: "HTML Entities",
    family: "encoding-text",
    pattern: "transform",
    description: "Encode or decode HTML character entities.",
    keywords: ["html", "entities", "encode", "decode"],
    designFrame: "HTML Entities (b9fWNy)",
  },
  {
    id: "hex-text",
    name: "Hex Text",
    family: "encoding-text",
    pattern: "transform",
    description: "Convert text to and from hexadecimal bytes.",
    keywords: ["hex", "text", "encode", "decode"],
    designFrame: "Hex Text (RhxHF)",
  },
  {
    id: "unicode-converter",
    name: "Unicode Converter",
    family: "encoding-text",
    pattern: "transform",
    description: "Convert Unicode characters and code points.",
    keywords: ["unicode", "codepoint", "utf"],
    designFrame: "Unicode Converter (DZFSs)",
  },
  {
    id: "binary-text",
    name: "Binary Text",
    family: "encoding-text",
    pattern: "transform",
    description: "Convert text to and from binary representation.",
    keywords: ["binary", "text", "bits"],
    designFrame: "Binary Text (Ldrhp)",
  },
  {
    id: "rot13-caesar",
    name: "ROT13 Caesar",
    family: "encoding-text",
    pattern: "transform",
    description: "Apply ROT13 and Caesar text shifts locally.",
    keywords: ["rot13", "caesar", "cipher"],
    designFrame: "ROT13 Caesar (QiDpT)",
  },
  {
    id: "morse-code",
    name: "Morse Code",
    family: "encoding-text",
    pattern: "transform",
    description: "Translate text to and from Morse code.",
    keywords: ["morse", "code", "translate"],
    designFrame: "Morse Code (c087C)",
  },
  {
    id: "sha-hash",
    name: "Hash (SHA)",
    family: "hash-crypto",
    pattern: "transform",
    description: "Compute SHA hashes locally for supplied input.",
    keywords: ["sha", "hash", "sha256", "sha512"],
    designFrame: "Hash (SHA) (U1lUQ0)",
  },
  {
    id: "hmac-generator",
    name: "HMAC Generator",
    family: "hash-crypto",
    pattern: "transform",
    description: "Generate an HMAC for local input and key material.",
    keywords: ["hmac", "hash", "signature"],
    designFrame: "HMAC Generator (p0yzv)",
  },
  {
    id: "aes-cipher",
    name: "AES Cipher",
    family: "hash-crypto",
    pattern: "transform",
    description: "Encrypt or decrypt text using explicit local AES settings.",
    keywords: ["aes", "encrypt", "decrypt", "cipher"],
    designFrame: "AES Cipher (zes65)",
  },
  {
    id: "bcrypt-hash",
    name: "Bcrypt Hash",
    family: "hash-crypto",
    pattern: "transform",
    description: "Create and verify bcrypt password hashes locally.",
    keywords: ["bcrypt", "password", "hash"],
    designFrame: "Bcrypt Hash (nWBbg)",
  },
  {
    id: "jwt-decoder",
    name: "JWT Decoder",
    family: "hash-crypto",
    pattern: "inspect",
    description: "Inspect JWT header and claims without sending the token away.",
    keywords: ["jwt", "token", "decode", "claims"],
    designFrame: "JWT Decoder (R5HFcw)",
  },
  {
    id: "token-generator",
    name: "Token Generator",
    family: "hash-crypto",
    pattern: "generate",
    description: "Generate local random tokens with explicit format controls.",
    keywords: ["token", "secret", "random", "generate"],
    designFrame: "Token Generator (KHKID)",
  },
  {
    id: "rsa-key-pair",
    name: "RSA Key Pair",
    family: "hash-crypto",
    pattern: "generate",
    description: "Generate an RSA key pair locally.",
    keywords: ["rsa", "key", "pem", "generate"],
    designFrame: "RSA Key Pair (Oi5nT)",
  },
  {
    id: "uuid-id",
    name: "UUID / ID",
    family: "generators",
    pattern: "generate",
    description: "Generate UUIDs and common identifier formats.",
    keywords: ["uuid", "guid", "id", "generate"],
    designFrame: "UUID / ID (TSKpr)",
  },
  {
    id: "url-parser",
    name: "URL Parser",
    family: "time-network",
    pattern: "inspect",
    description: "Inspect URL parts, query parameters, and encoding.",
    keywords: ["url", "parse", "query", "host"],
    designFrame: "URL Parser (H1TZfA)",
  },
  {
    id: "http-status-codes",
    name: "HTTP Status Codes",
    family: "time-network",
    pattern: "inspect",
    description: "Look up and filter HTTP response status codes.",
    keywords: ["http", "status", "response", "codes"],
    designFrame: "HTTP Status Codes (LjXun)",
  },
  {
    id: "mime-types",
    name: "MIME Types",
    family: "time-network",
    pattern: "inspect",
    description: "Look up MIME types and file extensions.",
    keywords: ["mime", "content-type", "extension"],
    designFrame: "MIME Types (A9PoHZ)",
  },
  {
    id: "user-agent-parser",
    name: "User Agent Parser",
    family: "time-network",
    pattern: "inspect",
    description: "Parse browser and device details from a user-agent string.",
    keywords: ["user-agent", "browser", "device", "parse"],
    designFrame: "User Agent Parser (pjnzX)",
  },
  {
    id: "basic-auth-header",
    name: "Basic Auth Header",
    family: "hash-crypto",
    pattern: "transform",
    description: "Build or inspect a Basic Authorization header locally.",
    keywords: ["basic", "auth", "header", "authorization"],
    designFrame: "Basic Auth Header (eYC3i)",
  },
  {
    id: "curl-converter",
    name: "cURL Converter",
    family: "time-network",
    pattern: "transform",
    description: "Convert cURL commands into useful request representations.",
    keywords: ["curl", "http", "request", "convert"],
    designFrame: "cURL Converter (J2LJzD)",
  },
  {
    id: "cron-parser",
    name: "Cron Parser",
    family: "time-network",
    pattern: "inspect",
    description: "Explain and preview cron schedules.",
    keywords: ["cron", "schedule", "time"],
    designFrame: "Cron Parser (XENy7)",
  },
  {
    id: "ip-subnet-calculator",
    name: "IP Subnet Calculator",
    family: "time-network",
    pattern: "inspect",
    description: "Calculate subnet ranges and CIDR notation.",
    keywords: ["ip", "subnet", "cidr", "network"],
    designFrame: "IP Subnet Calculator (CZ1jx)",
  },
  {
    id: "text-stats",
    name: "Text Stats",
    family: "text-regex",
    pattern: "inspect",
    description: "Measure characters, words, lines, and text composition.",
    keywords: ["text", "stats", "words", "characters"],
    designFrame: "Text Stats (fxy2c)",
  },
  {
    id: "text-diff",
    name: "Text Diff",
    family: "text-regex",
    pattern: "diff",
    description: "Compare two text values with a readable diff.",
    keywords: ["text", "diff", "compare"],
    designFrame: "Text Diff (J4CAnG)",
  },
  {
    id: "case-converter",
    name: "Case Converter",
    family: "text-regex",
    pattern: "transform",
    description: "Convert text between common naming conventions.",
    keywords: ["case", "camel", "snake", "kebab"],
    designFrame: "Case Converter (iKwdM)",
  },
  {
    id: "sort-lines",
    name: "Sort Lines",
    family: "text-regex",
    pattern: "transform",
    description: "Sort lines with explicit text options.",
    keywords: ["sort", "lines", "text"],
    designFrame: "Sort Lines (bNW0i)",
  },
  {
    id: "dedupe-lines",
    name: "Dedupe Lines",
    family: "text-regex",
    pattern: "transform",
    description: "Remove duplicate lines from local text.",
    keywords: ["dedupe", "duplicate", "lines"],
    designFrame: "Dedupe Lines (Kg081)",
  },
  {
    id: "lorem-ipsum",
    name: "Lorem Ipsum",
    family: "generators",
    pattern: "generate",
    description: "Generate placeholder copy with controllable length.",
    keywords: ["lorem", "ipsum", "placeholder", "generate"],
    designFrame: "Lorem Ipsum (J65Q8)",
  },
  {
    id: "text-reverser",
    name: "Text Reverser",
    family: "text-regex",
    pattern: "transform",
    description: "Reverse text by characters, words, or lines.",
    keywords: ["text", "reverse", "lines"],
    designFrame: "Text Reverser (H9EgGy)",
  },
  {
    id: "regex-tester",
    name: "Regex Tester",
    family: "text-regex",
    pattern: "inspect",
    description: "Test regular expressions against local sample text.",
    keywords: ["regex", "regular expression", "test", "match"],
    designFrame: "Regex Tester (rDpjQ)",
  },
  {
    id: "password-generator",
    name: "Password Generator",
    family: "generators",
    pattern: "generate",
    description: "Generate local passwords from explicit policies.",
    keywords: ["password", "random", "generate", "secret"],
    designFrame: "Password Generator (DLGia)",
  },
  {
    id: "nanoid-generator",
    name: "NanoID Generator",
    family: "generators",
    pattern: "generate",
    description: "Generate NanoID values locally.",
    keywords: ["nanoid", "id", "generate"],
    designFrame: "NanoID Generator (h4DC8)",
  },
  {
    id: "ulid-generator",
    name: "ULID Generator",
    family: "generators",
    pattern: "generate",
    description: "Generate sortable ULID values locally.",
    keywords: ["ulid", "id", "generate"],
    designFrame: "ULID Generator (CnASb)",
  },
  {
    id: "objectid-generator",
    name: "ObjectID Generator",
    family: "generators",
    pattern: "generate",
    description: "Generate MongoDB-style ObjectID values locally.",
    keywords: ["objectid", "mongodb", "id", "generate"],
    designFrame: "ObjectID Generator (Rl1Bm)",
  },
  {
    id: "mock-data",
    name: "Mock Data",
    family: "generators",
    pattern: "generate",
    description: "Generate configurable local fixture data.",
    keywords: ["mock", "fixture", "data", "generate"],
    designFrame: "Mock Data (nmkdk)",
  },
  {
    id: "random-port",
    name: "Random Port",
    family: "generators",
    pattern: "generate",
    description: "Generate an available-looking port number for development.",
    keywords: ["port", "random", "network", "generate"],
    designFrame: "Random Port (yahX9)",
  },
  {
    id: "random-number",
    name: "Random Number",
    family: "generators",
    pattern: "generate",
    description: "Generate random numbers within explicit bounds.",
    keywords: ["random", "number", "generate"],
    designFrame: "Random Number (a1wdtS)",
  },
  {
    id: "qr-code",
    name: "QR Code",
    family: "generators",
    pattern: "generate",
    description: "Generate a QR code from local text or a URL.",
    keywords: ["qr", "code", "generate", "url"],
    designFrame: "QR Code (ryifn)",
  },
  {
    id: "unix-timestamp",
    name: "Unix Timestamp",
    family: "time-network",
    pattern: "transform",
    description: "Convert Unix timestamps and human-readable dates.",
    keywords: ["unix", "timestamp", "date", "epoch"],
    designFrame: "Unix Timestamp (p3FVq)",
  },
  {
    id: "date-calculator",
    name: "Date Calculator",
    family: "time-network",
    pattern: "inspect",
    description: "Calculate intervals and offsets between dates.",
    keywords: ["date", "calculator", "duration"],
    designFrame: "Date Calculator (WE1Ij)",
  },
  {
    id: "timezone-converter",
    name: "Timezone Converter",
    family: "time-network",
    pattern: "transform",
    description: "Convert a time between named time zones.",
    keywords: ["timezone", "time", "convert", "utc"],
    designFrame: "Timezone Converter (qYlMU)",
  },
  {
    id: "duration-formatter",
    name: "Duration Formatter",
    family: "time-network",
    pattern: "transform",
    description: "Format and convert duration values.",
    keywords: ["duration", "time", "format"],
    designFrame: "Duration Formatter (dVb5J)",
  },
  {
    id: "number-base",
    name: "Number Base",
    family: "time-network",
    pattern: "transform",
    description: "Convert numbers between binary, decimal, hexadecimal, and more.",
    keywords: ["number", "base", "binary", "hex"],
    designFrame: "Number Base (vY4K3)",
  },
  {
    id: "color-converter",
    name: "Color Converter",
    family: "time-network",
    pattern: "transform",
    description: "Convert colors between common developer formats.",
    keywords: ["color", "hex", "rgb", "hsl"],
    designFrame: "Color Converter (kX9ZC)",
  },
  {
    id: "temperature",
    name: "Temperature",
    family: "time-network",
    pattern: "transform",
    description: "Convert temperatures between standard units.",
    keywords: ["temperature", "celsius", "fahrenheit", "kelvin"],
    designFrame: "Temperature (EWuTR)",
  },
  {
    id: "data-size",
    name: "Data Size",
    family: "time-network",
    pattern: "transform",
    description: "Convert data sizes across bytes and binary units.",
    keywords: ["data", "bytes", "kb", "mb", "size"],
    designFrame: "Data Size (d07Zls)",
  },
  {
    id: "age-calculator",
    name: "Age Calculator",
    family: "time-network",
    pattern: "inspect",
    description: "Calculate age and date intervals locally.",
    keywords: ["age", "date", "calculator"],
    designFrame: "Age Calculator (XjVrH)",
  },
  {
    id: "json-to-typescript",
    name: "JSON → TypeScript",
    family: "json-markup",
    pattern: "transform",
    description: "Create TypeScript type declarations from JSON samples.",
    keywords: ["json", "typescript", "types", "convert"],
    designFrame: "JSON → TypeScript (t9KwK)",
  },
  {
    id: "json-to-js-const",
    name: "JSON → JS / const",
    family: "json-markup",
    pattern: "transform",
    description: "Create JavaScript constants from JSON values.",
    keywords: ["json", "javascript", "const", "convert"],
    designFrame: "JSON → JS / const (nSQLS)",
  },
  {
    id: "html-to-jsx",
    name: "HTML → JSX",
    family: "json-markup",
    pattern: "transform",
    description: "Convert HTML markup into JSX.",
    keywords: ["html", "jsx", "react", "convert"],
    designFrame: "HTML → JSX (GDCpP)",
  },
  {
    id: "json-escape",
    name: "JSON Escape",
    family: "json-markup",
    pattern: "transform",
    description: "Escape or unescape strings for JSON safely.",
    keywords: ["json", "escape", "unescape", "string"],
    designFrame: "JSON Escape (W5XdLy)",
  },
  {
    id: "split-to-newlines",
    name: "Split → Newlines",
    family: "text-regex",
    pattern: "transform",
    description: "Split delimited text into one value per line.",
    keywords: ["split", "newlines", "delimiter", "text"],
    designFrame: "Split → Newlines (uZitj)",
  },
] as const satisfies readonly PlannedToolSpec[];

export const plannedTools = plannedToolSpecs.map(plannedTool);
