import { defineTool } from "../define-tool";
import type { ToolDefinition } from "../types";

const webTransformPlatforms = Object.freeze({
  web: {
    status: "available" as const,
    capabilities: ["transform-text", "clipboard-write"] as const,
  },
  "browser-extension": { status: "planned" as const, capabilities: ["transform-text"] as const },
  "vscode-extension": { status: "planned" as const, capabilities: ["transform-text"] as const },
});

/** Individually verified post-foundation tools. */
export const waveFourTools = [
  defineTool({
    id: "rot13-caesar",
    slug: "rot13-caesar",
    name: "ROT13 Caesar",
    shortName: "ROT13 Caesar",
    family: "encoding-text",
    pattern: "transform",
    status: "available",
    releaseStage: "implemented",
    description: "Apply ROT13 and Caesar text shifts locally.",
    keywords: ["rot13", "caesar", "cipher"],
    designFrame: "ROT13 Caesar (QiDpT)",
    platforms: webTransformPlatforms,
  }),
  defineTool({
    id: "sha-hash",
    slug: "sha-hash",
    name: "Hash (SHA)",
    shortName: "SHA Hash",
    family: "hash-crypto",
    pattern: "transform",
    status: "available",
    releaseStage: "implemented",
    description: "Compute SHA-256 digests locally for supplied UTF-8 text.",
    keywords: ["sha", "hash", "sha256", "digest"],
    designFrame: "Hash (SHA) (U1lUQ0)",
    platforms: webTransformPlatforms,
  }),
  defineTool({
    id: "hmac-generator",
    slug: "hmac-generator",
    name: "HMAC Generator",
    shortName: "HMAC",
    family: "hash-crypto",
    pattern: "transform",
    status: "available",
    releaseStage: "implemented",
    description: "Create HMAC-SHA-256 signatures locally from a secret and message.",
    keywords: ["hmac", "sha256", "signature", "keyed hash"],
    designFrame: "HMAC Generator (p0yzv)",
    platforms: webTransformPlatforms,
  }),
  defineTool({
    id: "bcrypt-hash",
    slug: "bcrypt-hash",
    name: "Bcrypt Hash",
    shortName: "Bcrypt",
    family: "hash-crypto",
    pattern: "transform",
    status: "available",
    releaseStage: "implemented",
    description: "Create and verify bcrypt password hashes locally.",
    keywords: ["bcrypt", "password", "hash"],
    designFrame: "Bcrypt Hash (nWBbg)",
    platforms: webTransformPlatforms,
  }),
  defineTool({
    id: "aes-cipher",
    slug: "aes-cipher",
    name: "AES Cipher",
    shortName: "AES Cipher",
    family: "hash-crypto",
    pattern: "transform",
    status: "available",
    releaseStage: "implemented",
    description: "Encrypt and decrypt UTF-8 text locally with AES-256-GCM.",
    keywords: ["aes", "encrypt", "decrypt", "gcm"],
    designFrame: "AES Cipher (zes65)",
    platforms: webTransformPlatforms,
  }),
  defineTool({
    id: "jwt-decoder",
    slug: "jwt-decoder",
    name: "JWT Decoder",
    shortName: "JWT Decoder",
    family: "hash-crypto",
    pattern: "inspect",
    status: "available",
    releaseStage: "implemented",
    description: "Inspect JWT header and claims locally without signature verification.",
    keywords: ["jwt", "token", "decode", "claims"],
    designFrame: "JWT Decoder (R5HFcw)",
    platforms: webTransformPlatforms,
  }),
  defineTool({
    id: "token-generator",
    slug: "token-generator",
    name: "Token Generator",
    shortName: "Token Generator",
    family: "hash-crypto",
    pattern: "generate",
    status: "available",
    releaseStage: "implemented",
    description: "Generate cryptographically secure local tokens.",
    keywords: ["token", "secret", "random", "generate"],
    designFrame: "Token Generator (KHKID)",
    platforms: webTransformPlatforms,
  }),
  defineTool({
    id: "rsa-key-pair",
    slug: "rsa-key-pair",
    name: "RSA Key Pair",
    shortName: "RSA Key Pair",
    family: "hash-crypto",
    pattern: "generate",
    status: "available",
    releaseStage: "implemented",
    description: "Generate an RSA-OAEP key pair locally.",
    keywords: ["rsa", "key", "pem", "generate"],
    designFrame: "RSA Key Pair (Oi5nT)",
    platforms: webTransformPlatforms,
  }),
  defineTool({
    id: "url-parser",
    slug: "url-parser",
    name: "URL Parser",
    shortName: "URL Parser",
    family: "time-network",
    pattern: "inspect",
    status: "available",
    releaseStage: "implemented",
    description: "Inspect URL parts and query parameters locally.",
    keywords: ["url", "parse", "query", "host"],
    designFrame: "URL Parser (H1TZfA)",
    platforms: webTransformPlatforms,
  }),
  defineTool({
    id: "http-status-codes",
    slug: "http-status-codes",
    name: "HTTP Status Codes",
    shortName: "HTTP Status",
    family: "time-network",
    pattern: "inspect",
    status: "available",
    releaseStage: "implemented",
    description: "Look up and filter HTTP response status codes.",
    keywords: ["http", "status", "response", "codes"],
    designFrame: "HTTP Status Codes (LjXun)",
    platforms: webTransformPlatforms,
  }),
  defineTool({
    id: "mime-types",
    slug: "mime-types",
    name: "MIME Types",
    shortName: "MIME Types",
    family: "time-network",
    pattern: "inspect",
    status: "available",
    releaseStage: "implemented",
    description: "Look up MIME types and file extensions locally.",
    keywords: ["mime", "content-type", "extension"],
    designFrame: "MIME Types (A9PoHZ)",
    platforms: webTransformPlatforms,
  }),
  defineTool({
    id: "user-agent-parser",
    slug: "user-agent-parser",
    name: "User Agent Parser",
    shortName: "User Agent",
    family: "time-network",
    pattern: "inspect",
    status: "available",
    releaseStage: "implemented",
    description: "Parse browser and device details from a user-agent string locally.",
    keywords: ["user-agent", "browser", "device", "parse"],
    designFrame: "User Agent Parser (pjnzX)",
    platforms: webTransformPlatforms,
  }),
  defineTool({
    id: "basic-auth-header",
    slug: "basic-auth-header",
    name: "Basic Auth Header",
    shortName: "Basic Auth",
    family: "hash-crypto",
    pattern: "transform",
    status: "available",
    releaseStage: "implemented",
    description: "Build or inspect a Basic Authorization header locally.",
    keywords: ["basic", "auth", "header", "authorization"],
    designFrame: "Basic Auth Header (eYC3i)",
    platforms: webTransformPlatforms,
  }),
  defineTool({
    id: "curl-converter",
    slug: "curl-converter",
    name: "cURL Converter",
    shortName: "cURL Converter",
    family: "time-network",
    pattern: "transform",
    status: "available",
    releaseStage: "implemented",
    description: "Convert a portable cURL request into copy-ready Fetch code locally.",
    keywords: ["curl", "http", "request", "fetch", "convert"],
    designFrame: "cURL Converter (J2LJzD)",
    platforms: webTransformPlatforms,
  }),
  defineTool({
    id: "cron-parser",
    slug: "cron-parser",
    name: "Cron Parser",
    shortName: "Cron Parser",
    family: "time-network",
    pattern: "inspect",
    status: "available",
    releaseStage: "implemented",
    description: "Explain five-field Unix cron schedules and preview their local-time runs.",
    keywords: ["cron", "schedule", "time", "parser"],
    designFrame: "Cron Parser (XENy7)",
    platforms: webTransformPlatforms,
  }),
  defineTool({
    id: "ip-subnet-calculator",
    slug: "ip-subnet-calculator",
    name: "IP Subnet Calculator",
    shortName: "IP Subnet",
    family: "time-network",
    pattern: "inspect",
    status: "available",
    releaseStage: "implemented",
    description: "Calculate IPv4 CIDR ranges, masks, and usable host counts locally.",
    keywords: ["ip", "subnet", "cidr", "network", "ipv4"],
    designFrame: "IP Subnet Calculator (CZ1jx)",
    platforms: webTransformPlatforms,
  }),
  defineTool({
    id: "password-generator",
    slug: "password-generator",
    name: "Password Generator",
    shortName: "Password Generator",
    family: "generators",
    pattern: "generate",
    status: "available",
    releaseStage: "implemented",
    description: "Generate policy-controlled passwords locally with Web Crypto.",
    keywords: ["password", "random", "generate", "secret"],
    designFrame: "Password Generator (DLGia)",
    platforms: webTransformPlatforms,
  }),
] as const satisfies readonly ToolDefinition[];
