import { defineTool } from "../define-tool";
import type { ToolDefinition } from "../types";

const webTransformPlatforms = Object.freeze({
  web: {
    status: "available" as const,
    capabilities: ["transform-text", "clipboard-write"] as const,
  },
  "browser-extension": { status: "planned" as const, capabilities: ["transform-text"] as const },
  "vscode-extension": { status: "planned" as const, capabilities: ["transform-text"] as const },
});

/** Individually verified post-foundation tools. */
export const waveFourTools = [
  defineTool({
    id: "rot13-caesar",
    slug: "rot13-caesar",
    name: "ROT13 Caesar",
    shortName: "ROT13 Caesar",
    family: "encoding-text",
    pattern: "transform",
    status: "available",
    releaseStage: "implemented",
    description: "Apply ROT13 and Caesar text shifts locally.",
    keywords: ["rot13", "caesar", "cipher"],
    designFrame: "ROT13 Caesar (QiDpT)",
    platforms: webTransformPlatforms,
  }),
  defineTool({
    id: "sha-hash",
    slug: "sha-hash",
    name: "Hash (SHA)",
    shortName: "SHA Hash",
    family: "hash-crypto",
    pattern: "transform",
    status: "available",
    releaseStage: "implemented",
    description: "Compute SHA-256 digests locally for supplied UTF-8 text.",
    keywords: ["sha", "hash", "sha256", "digest"],
    designFrame: "Hash (SHA) (U1lUQ0)",
    platforms: webTransformPlatforms,
  }),
  defineTool({
    id: "hmac-generator",
    slug: "hmac-generator",
    name: "HMAC Generator",
    shortName: "HMAC",
    family: "hash-crypto",
    pattern: "transform",
    status: "available",
    releaseStage: "implemented",
    description: "Create HMAC-SHA-256 signatures locally from a secret and message.",
    keywords: ["hmac", "sha256", "signature", "keyed hash"],
    designFrame: "HMAC Generator (p0yzv)",
    platforms: webTransformPlatforms,
  }),
  defineTool({
    id: "bcrypt-hash",
    slug: "bcrypt-hash",
    name: "Bcrypt Hash",
    shortName: "Bcrypt",
    family: "hash-crypto",
    pattern: "transform",
    status: "available",
    releaseStage: "implemented",
    description: "Create and verify bcrypt password hashes locally.",
    keywords: ["bcrypt", "password", "hash"],
    designFrame: "Bcrypt Hash (nWBbg)",
    platforms: webTransformPlatforms,
  }),
  defineTool({
    id: "aes-cipher",
    slug: "aes-cipher",
    name: "AES Cipher",
    shortName: "AES Cipher",
    family: "hash-crypto",
    pattern: "transform",
    status: "available",
    releaseStage: "implemented",
    description: "Encrypt and decrypt UTF-8 text locally with AES-256-GCM.",
    keywords: ["aes", "encrypt", "decrypt", "gcm"],
    designFrame: "AES Cipher (zes65)",
    platforms: webTransformPlatforms,
  }),
  defineTool({
    id: "jwt-decoder",
    slug: "jwt-decoder",
    name: "JWT Decoder",
    shortName: "JWT Decoder",
    family: "hash-crypto",
    pattern: "inspect",
    status: "available",
    releaseStage: "implemented",
    description: "Inspect JWT header and claims locally without signature verification.",
    keywords: ["jwt", "token", "decode", "claims"],
    designFrame: "JWT Decoder (R5HFcw)",
    platforms: webTransformPlatforms,
  }),
  defineTool({
    id: "token-generator",
    slug: "token-generator",
    name: "Token Generator",
    shortName: "Token Generator",
    family: "hash-crypto",
    pattern: "generate",
    status: "available",
    releaseStage: "implemented",
    description: "Generate cryptographically secure local tokens.",
    keywords: ["token", "secret", "random", "generate"],
    designFrame: "Token Generator (KHKID)",
    platforms: webTransformPlatforms,
  }),
  defineTool({
    id: "rsa-key-pair",
    slug: "rsa-key-pair",
    name: "RSA Key Pair",
    shortName: "RSA Key Pair",
    family: "hash-crypto",
    pattern: "generate",
    status: "available",
    releaseStage: "implemented",
    description: "Generate an RSA-OAEP key pair locally.",
    keywords: ["rsa", "key", "pem", "generate"],
    designFrame: "RSA Key Pair (Oi5nT)",
    platforms: webTransformPlatforms,
  }),
] as const satisfies readonly ToolDefinition[];
