import { useCopyFeedback } from "../hooks/useCopyFeedback";
import { useUuidGenerator } from "../hooks/useUuidGenerator";
import { Check, Copy, Fingerprint, RefreshCw, ShieldCheck, Trash2 } from "lucide-react";
import { useId } from "react";

export function UuidIdTool() {
  const headingId = useId();
  const { current, history, error: generationError, generate, clearHistory } = useUuidGenerator();
  const { isCopied, copy } = useCopyFeedback();

  const previousValues = current ? history.filter((val) => val !== current) : history;

  return (
    <div className="flex min-h-0 min-w-0 flex-1 flex-col gap-4 font-ui">
      {/* Tool Header */}
      <div className="flex items-center justify-between pb-1">
        <div className="flex items-center gap-3">
          <div className="size-11 bg-primary-soft border border-primary/30 rounded-[11px] text-primary flex items-center justify-center shrink-0">
            <Fingerprint className="size-5" />
          </div>
          <div>
            <h2
              id={headingId}
              className="text-[20px] font-bold font-display text-on-surface tracking-[-0.02em] m-0"
            >
              Generate UUIDs &amp; IDs
            </h2>
            <p className="text-[13px] text-on-muted m-0 mt-0.5">
              Create RFC 4122 UUID v4 identifiers locally with secure browser randomness.
            </p>
          </div>
        </div>
      </div>

      {/* Error alert */}
      {generationError && (
        <div
          role="alert"
          className="bg-danger-soft border border-danger/40 rounded-[10px] px-3.5 py-2 text-[12px] text-danger"
        >
          {generationError}
        </div>
      )}

      {/* Two-Column Layout */}
      <div className="grid grid-cols-1 lg:grid-cols-[minmax(280px,360px)_minmax(0,1fr)] gap-4 flex-1 min-h-[380px]">
        {/* Controls Card */}
        <div className="bg-surface-low border border-outline rounded-[12px] p-5 flex flex-col justify-between">
          <div className="flex flex-col gap-4">
            <span className="text-[11px] font-semibold text-on-muted uppercase tracking-wider">
              Version &amp; Format
            </span>
            <div className="flex flex-col gap-2 bg-surface border border-outline rounded-[8px] p-3 text-[12px]">
              <div className="flex items-center justify-between">
                <span className="text-on-muted">Version</span>
                <span className="font-mono font-semibold text-on-surface">v4 (random)</span>
              </div>
              <div className="flex items-center justify-between">
                <span className="text-on-muted">Variant</span>
                <span className="font-mono font-semibold text-on-surface">RFC 4122</span>
              </div>
              <div className="flex items-center justify-between">
                <span className="text-on-muted">Structure</span>
                <span className="font-mono font-semibold text-primary">8-4-4-4-12</span>
              </div>
            </div>

            <p className="text-[12px] leading-relaxed text-on-muted m-0">
              UUID v4 uses 122 bits of cryptographically secure pseudo-randomness generated by the
              browser's Web Crypto API.
            </p>
          </div>

          <button
            type="button"
            onClick={generate}
            className="mt-4 h-[38px] w-full rounded-[8px] bg-primary text-primary-foreground font-medium text-[13px] hover:bg-primary-strong transition-colors flex items-center justify-center gap-1.5 cursor-pointer shadow-sm"
          >
            <RefreshCw className="size-4" />
            Generate UUID
          </button>
        </div>

        {/* Output & History Card */}
        <section
          aria-label="Generated UUID"
          className="flex flex-col bg-surface-low border border-outline rounded-[12px] overflow-hidden"
        >
          <div className="h-[45.5px] bg-surface border-b border-outline px-4 flex items-center justify-between shrink-0">
            <div className="flex items-center gap-2">
              <span className="size-2 rounded-full bg-success" />
              <span className="text-[13px] font-medium text-on-surface">Generated UUID</span>
            </div>
            <button
              type="button"
              onClick={() => current && void copy("current", current)}
              disabled={!current}
              title={isCopied("current") ? "Copied" : "Copy"}
              aria-label={isCopied("current") ? "Copied generated UUID" : "Copy generated UUID"}
              className={`h-[32px] px-2.5 rounded-[7px] flex items-center gap-1.5 text-[12px] font-medium transition-colors cursor-pointer disabled:pointer-events-none disabled:opacity-30 ${
                isCopied("current")
                  ? "bg-success-soft text-success border border-success/40"
                  : "text-on-muted hover:text-on-surface hover:bg-surface border border-transparent hover:border-outline"
              }`}
            >
              {isCopied("current") ? (
                <>
                  <Check className="size-4 text-success" />
                  <span>Copied</span>
                </>
              ) : (
                <>
                  <Copy className="size-4" />
                  <span>Copy</span>
                </>
              )}
            </button>
          </div>

          <div className="p-5 flex flex-col gap-4 flex-1 overflow-y-auto">
            {/* Primary spotlight box */}
            <div className="bg-surface border border-outline rounded-[10px] p-4 flex flex-col gap-2">
              {current ? (
                <div className="font-mono text-[20px] font-bold text-success break-all select-all">
                  {current}
                </div>
              ) : (
                <div className="text-[13px] text-on-muted italic">
                  Click Generate UUID to create an RFC 4122 identifier…
                </div>
              )}
              <div className="flex items-center gap-1.5 text-[11px] text-on-muted font-mono">
                <ShieldCheck className="size-3.5 text-primary" />
                <span>RFC 4122 · v4 · 128-bit Cryptographically Secure</span>
              </div>
            </div>

            {/* History section */}
            {previousValues.length > 0 && (
              <div className="flex flex-col gap-2">
                <div className="flex items-center justify-between pt-2">
                  <span className="text-[11px] font-semibold text-on-muted uppercase tracking-wider">
                    Recent History ({previousValues.length})
                  </span>
                  <button
                    type="button"
                    onClick={clearHistory}
                    className="text-[11px] text-danger hover:underline flex items-center gap-1 cursor-pointer"
                  >
                    <Trash2 className="size-3" />
                    Clear
                  </button>
                </div>
                <div className="flex flex-col gap-1.5 max-h-[220px] overflow-y-auto">
                  {previousValues.map((val, idx) => (
                    <div
                      key={idx}
                      className="flex items-center justify-between p-2.5 rounded-[6px] bg-surface border border-outline text-[12px] font-mono text-on-surface"
                    >
                      <span className="truncate mr-2">{val}</span>
                      <button
                        type="button"
                        onClick={() => void copy(`hist-${idx}`, val)}
                        title={isCopied(`hist-${idx}`) ? "Copied" : "Copy this UUID"}
                        aria-label={isCopied(`hist-${idx}`) ? "Copied this UUID" : "Copy this UUID"}
                        className={`size-[26px] rounded-[6px] flex items-center justify-center transition-colors shrink-0 cursor-pointer ${
                          isCopied(`hist-${idx}`)
                            ? "bg-success-soft text-success border border-success/40"
                            : "text-on-muted hover:text-on-surface hover:bg-surface border border-transparent hover:border-outline"
                        }`}
                      >
                        {isCopied(`hist-${idx}`) ? (
                          <Check className="size-3.5 text-success" />
                        ) : (
                          <Copy className="size-3.5" />
                        )}
                      </button>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        </section>
      </div>

      {/* Status Bar */}
      <div className="h-[36px] bg-surface border border-outline rounded-[8px] px-3.5 flex items-center justify-between text-[12px] shrink-0 font-ui">
        <div className="flex items-center gap-3">
          <span
            className={`px-2 py-0.5 rounded-full text-[11px] font-semibold ${
              current ? "bg-success-soft text-success" : "bg-surface text-on-muted"
            }`}
          >
            {current ? "Generated" : "Ready"}
          </span>
          <span className="text-on-muted">
            {history.length > 0 ? `${history.length} generated this session` : "RFC 4122 v4"}
          </span>
        </div>
        <div className="flex items-center gap-2">
          <span className="text-primary-strong font-mono text-[11px] font-semibold">
            &lt;&gt; UUID
          </span>
        </div>
      </div>
    </div>
  );
}
