import { err, ok, type ToolResult } from "../result";

export type YamlValue =
  | null
  | boolean
  | number
  | string
  | YamlValue[]
  | { [key: string]: YamlValue };

export const YAML_CODEC_MAX_INPUT_CHARS = 1_000_000;
export const YAML_CODEC_MAX_OUTPUT_CHARS = 2_000_000;
export const YAML_CODEC_MAX_DEPTH = 128;
export const YAML_CODEC_MAX_NODES = 100_000;

type SourceLine = { readonly indent: number; readonly content: string; readonly line: number };
type ParseState = { readonly lines: readonly SourceLine[]; index: number; nodes: number };

/** Serialize JSON-compatible data as safe, deterministic YAML 1.2. */
export function stringifyYaml(value: YamlValue, indentSize: 2 | 4 = 2): ToolResult<string> {
  const writer = new BoundedWriter();
  const stack: Array<{
    readonly value: YamlValue;
    readonly indent: number;
    readonly prefix: string;
  }> = [{ value, indent: 0, prefix: "" }];
  let nodes = 0;

  while (stack.length > 0) {
    const frame = stack.pop();
    if (!frame) continue;
    nodes += 1;
    if (nodes > YAML_CODEC_MAX_NODES) return tooComplex("value");
    if (frame.indent / indentSize > YAML_CODEC_MAX_DEPTH) return tooDeep();

    const scalar = yamlScalar(frame.value);
    if (scalar !== null) {
      writer.write(" ".repeat(frame.indent));
      writer.write(prefixScalar(frame.prefix));
      writer.write(scalar);
      writer.write("\n");
      continue;
    }

    if (Array.isArray(frame.value)) {
      if (frame.value.length === 0) {
        writer.write(" ".repeat(frame.indent));
        writer.write(prefixScalar(frame.prefix));
        writer.write("[]\n");
        continue;
      }
      const childIndent = writeContainerPrefix(writer, frame.indent, frame.prefix, indentSize);
      for (let index = frame.value.length - 1; index >= 0; index -= 1) {
        stack.push({ value: frame.value[index] as YamlValue, indent: childIndent, prefix: "-" });
      }
      continue;
    }

    const entries = Object.entries(frame.value as { [key: string]: YamlValue });
    if (entries.length === 0) {
      writer.write(" ".repeat(frame.indent));
      writer.write(prefixScalar(frame.prefix));
      writer.write("{}\n");
      continue;
    }
    const childIndent = writeContainerPrefix(writer, frame.indent, frame.prefix, indentSize);
    for (let index = entries.length - 1; index >= 0; index -= 1) {
      const entry = entries[index];
      if (!entry) continue;
      const [key, child] = entry;
      stack.push({ value: child, indent: childIndent, prefix: `${quoteYaml(key)}:` });
    }
  }

  const output = writer.finish();
  return output.ok ? ok(output.value.trimStart()) : output;
}

/**
 * Parse the portable YAML subset generated by this suite plus common block
 * mappings/sequences and plain scalars. Anchors, tags, aliases, block scalars,
 * merge keys and multi-document streams are rejected rather than interpreted
 * ambiguously or unsafely.
 */
export function parseYaml(source: string): ToolResult<YamlValue> {
  if (source.length > YAML_CODEC_MAX_INPUT_CHARS) {
    return err(
      "INPUT_TOO_LARGE",
      `YAML input exceeds the ${YAML_CODEC_MAX_INPUT_CHARS.toLocaleString()} character limit.`,
    );
  }

  const prepared = prepareLines(source);
  if (!prepared.ok) return prepared;
  if (prepared.value.length === 0) return err("EMPTY_INPUT", "Enter a YAML document to convert.");
  const state: ParseState = { lines: prepared.value, index: 0, nodes: 0 };
  const parsed = parseBlock(state, prepared.value[0]?.indent ?? 0, 0);
  if (!parsed.ok) return parsed;
  if (state.index !== prepared.value.length) {
    const line = prepared.value[state.index];
    return syntaxError(line?.line ?? 1, "unexpected indentation");
  }
  return parsed;
}

function parseBlock(state: ParseState, indent: number, depth: number): ToolResult<YamlValue> {
  if (depth > YAML_CODEC_MAX_DEPTH) return tooDeep();
  const first = state.lines[state.index];
  if (!first) return syntaxError(1, "expected a value");
  if (first.indent !== indent) return syntaxError(first.line, "unexpected indentation");
  if (isSequenceLine(first.content)) return parseSequence(state, indent, depth);
  if (findKeyDelimiter(first.content) !== -1) return parseMapping(state, indent, depth);
  state.index += 1;
  return parseYamlScalar(first.content, first.line);
}

function parseSequence(state: ParseState, indent: number, depth: number): ToolResult<YamlValue[]> {
  const values: YamlValue[] = [];
  while (true) {
    const line = state.lines[state.index];
    if (!line || line.indent < indent) break;
    if (line.indent > indent) return syntaxError(line.line, "unexpected indentation in sequence");
    if (!isSequenceLine(line.content))
      return syntaxError(line.line, "cannot mix mapping and sequence entries");
    state.index += 1;
    const rest = line.content.slice(1).trimStart();
    const value = parseInlineOrChild(state, rest, indent, depth, line.line);
    if (!value.ok) return value;
    values.push(value.value);
    const node = countNode(state);
    if (!node.ok) return node;
  }
  return ok(values);
}

function parseMapping(
  state: ParseState,
  indent: number,
  depth: number,
): ToolResult<{ [key: string]: YamlValue }> {
  const output: { [key: string]: YamlValue } = Object.create(null) as { [key: string]: YamlValue };
  while (true) {
    const line = state.lines[state.index];
    if (!line || line.indent < indent) break;
    if (line.indent > indent) return syntaxError(line.line, "unexpected indentation in mapping");
    const delimiter = findKeyDelimiter(line.content);
    if (delimiter === -1 || isSequenceLine(line.content)) {
      return syntaxError(line.line, "cannot mix mapping and sequence entries");
    }
    const key = parseYamlKey(line.content.slice(0, delimiter).trim(), line.line);
    if (!key.ok) return key;
    if (Object.hasOwn(output, key.value))
      return syntaxError(line.line, `duplicate key ${JSON.stringify(key.value)}`);
    state.index += 1;
    const rest = line.content.slice(delimiter + 1).trimStart();
    const value = parseInlineOrChild(state, rest, indent, depth, line.line);
    if (!value.ok) return value;
    output[key.value] = value.value;
    const node = countNode(state);
    if (!node.ok) return node;
  }
  return ok(output);
}

function parseInlineOrChild(
  state: ParseState,
  rest: string,
  parentIndent: number,
  depth: number,
  line: number,
): ToolResult<YamlValue> {
  if (rest.length > 0) {
    if (isInlineMapping(rest)) return parseSequenceMapping(state, rest, parentIndent, depth, line);
    return parseYamlScalar(rest, line);
  }
  const child = state.lines[state.index];
  if (!child || child.indent <= parentIndent) return ok(null);
  return parseBlock(state, child.indent, depth + 1);
}

/** Parse the common YAML sequence form `- key: value` plus its sibling keys. */
function parseSequenceMapping(
  state: ParseState,
  source: string,
  sequenceIndent: number,
  depth: number,
  line: number,
): ToolResult<{ [key: string]: YamlValue }> {
  const delimiter = findKeyDelimiter(source);
  if (delimiter === -1) return syntaxError(line, "invalid sequence mapping");

  const key = parseYamlKey(source.slice(0, delimiter).trim(), line);
  if (!key.ok) return key;
  const rest = source.slice(delimiter + 1).trimStart();
  const value = rest ? parseYamlScalar(rest, line) : ok<YamlValue>(null);
  if (!value.ok) return value;

  const output: { [key: string]: YamlValue } = Object.create(null) as {
    [key: string]: YamlValue;
  };
  output[key.value] = value.value;

  const sibling = state.lines[state.index];
  if (!sibling || sibling.indent <= sequenceIndent) return ok(output);
  const mappingIndent = sequenceIndent + 2;
  if (sibling.indent !== mappingIndent) {
    return syntaxError(sibling.line, "unexpected indentation in sequence mapping");
  }

  const following = parseMapping(state, mappingIndent, depth + 1);
  if (!following.ok) return following;
  for (const [nextKey, nextValue] of Object.entries(following.value)) {
    if (Object.hasOwn(output, nextKey))
      return syntaxError(line, `duplicate key ${JSON.stringify(nextKey)}`);
    output[nextKey] = nextValue;
  }
  return ok(output);
}

function prepareLines(source: string): ToolResult<readonly SourceLine[]> {
  const lines: SourceLine[] = [];
  let sawStart = false;
  let sawEnd = false;
  for (const [index, raw] of source
    .replace(/^\uFEFF/, "")
    .split(/\r\n|\n|\r/)
    .entries()) {
    if (/\t/.test(raw)) return syntaxError(index + 1, "tabs are not supported for indentation");
    const withoutComment = stripComment(raw).trimEnd();
    const trimmed = withoutComment.trim();
    if (!trimmed) continue;
    if (sawEnd) return syntaxError(index + 1, "content after document end is not supported");
    if (trimmed === "---") {
      if (sawStart || lines.length > 0)
        return syntaxError(index + 1, "multiple YAML documents are not supported");
      sawStart = true;
      continue;
    }
    if (trimmed === "...") {
      sawEnd = true;
      continue;
    }
    if (/^(?:[!&*]|<<\s*:)/.test(trimmed)) {
      return syntaxError(index + 1, "tags, anchors, aliases, and merge keys are not supported");
    }
    const indent = withoutComment.length - withoutComment.trimStart().length;
    lines.push({ indent, content: withoutComment.slice(indent), line: index + 1 });
  }
  return ok(lines);
}

function parseYamlKey(source: string, line: number): ToolResult<string> {
  if (!source) return syntaxError(line, "mapping keys cannot be empty");
  const scalar = parseYamlScalar(source, line);
  if (!scalar.ok) return scalar;
  if (typeof scalar.value !== "string") return syntaxError(line, "mapping keys must be strings");
  return ok(scalar.value);
}

function parseYamlScalar(source: string, line: number): ToolResult<YamlValue> {
  if (/^[!&*]/.test(source))
    return syntaxError(line, "tags, anchors, and aliases are not supported");
  if (source === "[]") return ok([]);
  if (source === "{}") return ok({});
  if (source.startsWith("[") || source.startsWith("{")) {
    try {
      return ok(JSON.parse(source) as YamlValue);
    } catch {
      return syntaxError(line, "flow collections must use valid JSON syntax");
    }
  }
  if (source.startsWith('"')) {
    try {
      const parsed = JSON.parse(source) as unknown;
      return typeof parsed === "string"
        ? ok(parsed)
        : syntaxError(line, "quoted scalar must be a string");
    } catch {
      return syntaxError(line, "invalid double-quoted string");
    }
  }
  if (source.startsWith("'")) {
    if (!source.endsWith("'") || source.length < 2)
      return syntaxError(line, "invalid single-quoted string");
    return ok(source.slice(1, -1).replaceAll("''", "'"));
  }
  if (source === "null" || source === "Null" || source === "NULL" || source === "~")
    return ok(null);
  if (source === "true" || source === "True" || source === "TRUE") return ok(true);
  if (source === "false" || source === "False" || source === "FALSE") return ok(false);
  if (/^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$/.test(source)) {
    const value = Number(source);
    return Number.isFinite(value) ? ok(value) : syntaxError(line, "number must be finite");
  }
  if (
    source.includes("[") ||
    source.includes("]") ||
    source.includes("{") ||
    source.includes("}") ||
    source.includes(",") ||
    /\s:\s/.test(source)
  ) {
    return syntaxError(line, "quote this scalar to use YAML punctuation");
  }
  return ok(source);
}

function yamlScalar(value: YamlValue): string | null {
  if (value === null) return "null";
  if (typeof value === "boolean" || typeof value === "number") return String(value);
  if (typeof value === "string") return quoteYaml(value);
  return null;
}

function quoteYaml(value: string): string {
  return JSON.stringify(value);
}

function prefixScalar(prefix: string): string {
  if (!prefix) return "";
  return `${prefix} `;
}

function writeContainerPrefix(
  writer: BoundedWriter,
  indent: number,
  prefix: string,
  indentSize: number,
): number {
  if (!prefix) return indent;
  writer.write(" ".repeat(indent));
  writer.write(prefix);
  writer.write("\n");
  return indent + indentSize;
}

function isSequenceLine(content: string): boolean {
  return content === "-" || content.startsWith("- ");
}

function findKeyDelimiter(content: string): number {
  let quote: "'" | '"' | null = null;
  for (let index = 0; index < content.length; index += 1) {
    const char = content[index];
    if (char === undefined) continue;
    if (quote === '"' && char === "\\") {
      index += 1;
      continue;
    }
    if (char === '"' || char === "'") {
      if (quote === char) quote = null;
      else if (quote === null) quote = char;
      continue;
    }
    if (
      char === ":" &&
      quote === null &&
      (index === content.length - 1 || /\s/u.test(content[index + 1] ?? ""))
    )
      return index;
  }
  return -1;
}

function isInlineMapping(content: string): boolean {
  return findKeyDelimiter(content) !== -1;
}

function stripComment(line: string): string {
  let quote: "'" | '"' | null = null;
  for (let index = 0; index < line.length; index += 1) {
    const char = line[index];
    if (char === undefined) continue;
    if (quote === '"' && char === "\\") {
      index += 1;
      continue;
    }
    if (char === '"' || char === "'") {
      if (quote === char) quote = null;
      else if (quote === null) quote = char;
      continue;
    }
    if (char === "#" && quote === null && (index === 0 || /\s/.test(line[index - 1] ?? ""))) {
      return line.slice(0, index);
    }
  }
  return line;
}

function countNode(state: ParseState): ToolResult<void> {
  state.nodes += 1;
  return state.nodes > YAML_CODEC_MAX_NODES ? tooComplex("value") : ok(undefined);
}

function syntaxError(line: number, message: string): ToolResult<never> {
  return err("INVALID_YAML", `YAML is invalid on line ${line}: ${message}.`);
}

function tooComplex(noun: string): ToolResult<never> {
  return err(
    "INPUT_TOO_COMPLEX",
    `YAML ${noun} count exceeds the ${YAML_CODEC_MAX_NODES.toLocaleString()} limit.`,
  );
}

function tooDeep(): ToolResult<never> {
  return err("INPUT_TOO_DEEP", `YAML nesting exceeds the ${YAML_CODEC_MAX_DEPTH}-level limit.`);
}

class BoundedWriter {
  private parts: string[] = [];
  private length = 0;

  write(value: string): void {
    this.length += value.length;
    if (this.length <= YAML_CODEC_MAX_OUTPUT_CHARS) this.parts.push(value);
  }

  finish(): ToolResult<string> {
    if (this.length > YAML_CODEC_MAX_OUTPUT_CHARS) {
      return err(
        "OUTPUT_TOO_LARGE",
        `YAML output exceeds the ${YAML_CODEC_MAX_OUTPUT_CHARS.toLocaleString()} character limit.`,
      );
    }
    return ok(this.parts.join(""));
  }
}
